### ISSUE TITLE
Errors when use 1.17.0 to build apiserver-aggregation

### ISSUE THREAD

**Issue by xjtustt** [kubernetes-sigs/apiserver-builder-alpha#501] opened 2020-05-15 17:32 UTC
I use apiserver-boot 1.17.0 to build an apiserver-aggreation. I will create a REST resource and only use the Get and List method.

So when  run `apiserver-boot create group version resource`, I only type `y` for resource(`n` for both controller and admission controller).

When run the apiserver-aggregation, I can see tons of these errors,
```
E0515 17:07:05.664439       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to watch *v1.ConfigMap: unknown (get configmaps)
E0515 17:07:05.664840       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to watch *v1.ConfigMap: unknown (get configmaps)
E0515 17:07:05.918040       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource
E0515 17:07:06.059478       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1.MutatingWebhookConfiguration: the server could not find the requested resource
```
For now the Get/List work as expected, but I need to confirm the root cause of the errors.
Can someone help me about this?

**Comment by yue9944882** [comment] 2020-05-21 06:41
the errors from list-watching [mutating|validating]webhookconfigurations is a duplicate of #500. switching off these plugins should work. while as for list-watching configmap, there's a new internal controller `ConfigMapCAController` introduced in the latest releases https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go#L39-L41 it is basically used to manage in-cluster CA setups, which is irrelavant w/ the aggregated apiserver. i suppose adding a flag `--authentication-skip-lookup=true` should get rid of that error..

**Comment by xjtustt** [comment] 2020-05-21 06:57
Duplicate with #500

**Comment by xjtustt** [comment] 2020-05-22 02:46
@yue9944882 I need to reopen this issue since I found some other issues.
Let me give you some background information about this issue and #500 .

I use apiserver-boot to add a apiserver-aggregation layer for k8s and I only add a rest resource called `MeteringReport`(there are detail steps in #500 ).
My expected behavior is that user can use `kubectl` to get/list the resource `MeteringReport`.

Before I add `--authentication-skip-lookup=true` and `--disable-admission-plugins= NamespaceLifecycle,MutatingAdmissionWebhook,ValidatingAdmissionWebhook` you tell me, the behavior is that:
1. the apiserver-aggregation can be started with no errors
2. but after some hours(maybe 10+ hours) there existing lots errors like what I show before. At this time, user can not use `kubectl get meteringreport` to list/get rest resource.

After I add the two flags, the behavior is that:
1. the apiserver-aggregation can be started with no errors
2. but after some hours(maybe 10+ hours), user cannot use `kubectl get meteringreport` to list/get rest resource. At this time the apiserver-aggregation throws NO ERRORS.

Below is the error logs when user use this command `kubectl get meteringreport -v=8`

```
I0521 19:11:19.696062    9527 loader.go:375] Config loaded from file:  /root/auth/kubeconfig
I0521 19:11:19.701133    9527 round_trippers.go:420] GET https://api.ouzos.os.fyre.ibm.com:6443/apis/metering.ibm.com/v1?timeout=32s
I0521 19:11:19.701165    9527 round_trippers.go:427] Request Headers:
I0521 19:11:19.701178    9527 round_trippers.go:431]     Accept: application/json, */*
I0521 19:11:19.701189    9527 round_trippers.go:431]     User-Agent: kubectl/v0.0.0 (linux/amd64) kubernetes/$Format
I0521 19:11:19.701204    9527 round_trippers.go:431]     Authorization: Bearer <masked>
I0521 19:11:19.930325    9527 round_trippers.go:446] Response Status: 503 Service Unavailable in 229 milliseconds
I0521 19:11:19.930353    9527 round_trippers.go:449] Response Headers:
I0521 19:11:19.930362    9527 round_trippers.go:452]     Cache-Control: no-cache, private
I0521 19:11:19.930368    9527 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
I0521 19:11:19.930373    9527 round_trippers.go:452]     X-Content-Type-Options: nosniff
I0521 19:11:19.930378    9527 round_trippers.go:452]     Content-Length: 20
I0521 19:11:19.930383    9527 round_trippers.go:452]     Date: Fri, 22 May 2020 02:11:19 GMT
I0521 19:11:19.952703    9527 request.go:968] Response Body: service unavailable
I0521 19:11:19.958529    9527 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0521 19:11:19.958593    9527 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request

I0521 19:11:20.799094    9527 request.go:968] Response Body: service unavailable
I0521 19:11:21.165636    9527 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0521 19:11:21.165686    9527 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
F0521 19:11:21.172909    9527 helpers.go:114] error: the server doesn't have a resource type "meteringreports"

```

Do yo know the root cause of this?

**Comment by yue9944882** [comment] 2020-05-22 04:39
@xjtustt can you check if there's error status on your registered `APIService` resource? 503 normally suggests something's wrong w/ the APIService configuration (instead of apiserver itself)

**Comment by xjtustt** [comment] 2020-05-22 05:56
@yue9944882 
Thank you for your feedback. Since I have restarted the container so now the status of APIService looks good. Could you help me to check whether the configuration is correct?
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2020-05-21T06:05:36Z"
  labels:
  name: v1.metering.ibm.com
spec:
  group: metering.ibm.com
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: metering-report
    namespace: <ns-name>
    port: 443
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2020-05-22T02:20:04Z"
    message: all checks passed
    reason: Passed
    status: "True"
    type: Available
```

Besides, I want to describe some more about how I do the authentication.
At the first step, I followed this [document](https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/docs/running_in_cluster.md#build-the-config) to generate the installing yaml file(including APIService, Service, Deployment, etc.). I noticed that the APIService contains an `CABundle` field.

But I found that this will be expired in one year then I found [metrics-server](https://github.com/kubernetes-sigs/metrics-server) do the authentication like [this](https://github.com/kubernetes-sigs/metrics-server/blob/b36cb6ef57aa2f12c55fedc0903f6c8d78c37fd5/deploy/1.8%2B/metrics-server-deployment.yaml#L35). So I use the same way. 

This will be work in the k8s 1.12 but some days before I need to upgrade to go mod so I use apiserver-boot 1.17 to regenerated my project. After that I found some logs when the apiserver-aggregation starts,
```
I0522 02:18:35.349742       1 serving.go:306] Generated self-signed cert (/tmp/apiserver.crt, /tmp/apiserver.key)
I0522 02:18:35.349913       1 start.go:359] loading in-cluster loopback client...
W0522 02:18:36.150462       1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::client-ca-file" due to: configmap "extension-apiserver-authentication" not found
W0522 02:18:36.150564       1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file" due to: configmap "extension-apiserver-authentication" not found
I0522 02:18:36.275179       1 configmap_cafile_content.go:205] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0522 02:18:36.275235       1 shared_informer.go:197] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0522 02:18:36.275275       1 configmap_cafile_content.go:205] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0522 02:18:36.275314       1 shared_informer.go:197] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0522 02:18:36.275703       1 dynamic_serving_content.go:129] Starting serving-cert::/tmp/apiserver.crt::/tmp/apiserver.key
I0522 02:18:36.276051       1 secure_serving.go:178] Serving securely on [::]:7443
```

Not sure that the logging shows `unable to load initial CA bundle` is an expect behavior or not.

**Comment by yue9944882** [comment] 2020-05-22 12:46
> Could you help me to check whether the configuration is correct?

@xjtustt ur apiservice should work as far as i can tell. and the status shows that the connectivity is good.

> Not sure that the logging shows unable to load initial CA bundle is an expect behavior or not.


> W0522 02:18:36.150462       1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::client-ca-file" due to: configmap "extension-apiserver-authentication" not found
W0522 02:18:36.150564       1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file" due to: configmap "extension-apiserver-authentication" not found

i think these lines are just mild warnings. it's thrown from a newly-introduced controller inside the apiserver framework which enables the apiserver to perform in-flight certificate rotation. it wont break anything if the controller didn't start properly. you always have the option to upgrade your certs by manual certs replacing ;)

**Comment by xjtustt** [comment] 2020-05-22 16:38
> @xjtustt can you check if there's error status on your registered `APIService` resource? 503 normally suggests something's wrong w/ the APIService configuration (instead of apiserver itself)

@yue9944882 ,
I reproduced this issue again, at this time, APIService status is GOOD,
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2020-05-20T22:58:40Z"
  labels:
  name: v1.metering.ibm.com
  ownerReferences:
  resourceVersion: "1086706"
  selfLink: /apis/apiregistration.k8s.io/v1/apiservices/v1.metering.ibm.com
spec:
  group: metering.ibm.com
  groupPriorityMinimum: 1000
  insecureSkipTLSVerify: true
  service:
    name: metering-report
    namespace: ibm-common-services
    port: 443
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2020-05-22T02:08:59Z"
    message: all checks passed
    reason: Passed
    status: "True"
    type: Available
```
 When I use `kubectl get meteringreport -v=8` I found some errors:
```
I0522 09:28:02.061487   32016 loader.go:359] Config loaded from file /root/auth/kubeconfig
I0522 09:28:02.075242   32016 round_trippers.go:416] GET https://api.<host-name>:6443/apis/metering.ibm.com/v1?timeout=32s
I0522 09:28:02.075274   32016 round_trippers.go:423] Request Headers:
I0522 09:28:02.075286   32016 round_trippers.go:426]     Accept: application/json, */*
I0522 09:28:02.075295   32016 round_trippers.go:426]     User-Agent: kubectl/v0.0.0 (linux/amd64) kubernetes/$Format
I0522 09:28:02.075309   32016 round_trippers.go:426]     Authorization: Bearer yHLjXyDVkkchCTBVLvhsWN9HxNug-codJnS_49f2O0Y
I0522 09:28:02.412077   32016 round_trippers.go:441] Response Status: 500 Internal Server Error in 336 milliseconds
I0522 09:28:02.412121   32016 round_trippers.go:444] Response Headers:
I0522 09:28:02.412144   32016 round_trippers.go:447]     Content-Type: text/plain; charset=utf-8
I0522 09:28:02.412161   32016 round_trippers.go:447]     Date: Fri, 22 May 2020 16:28:02 GMT
I0522 09:28:02.412174   32016 round_trippers.go:447]     X-Content-Type-Options: nosniff
I0522 09:28:02.412186   32016 round_trippers.go:447]     Content-Length: 190
I0522 09:28:02.412198   32016 round_trippers.go:447]     Cache-Control: no-cache, private
I0522 09:28:02.421716   32016 request.go:942] Response Body: Internal Server Error: "/apis/metering.ibm.com/v1?timeout=32s": Post https://172.30.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews: http2: no cached connection was available
I0522 09:28:02.429359   32016 request.go:1145] body was not decodable (unable to check for Status): yaml: mapping values are not allowed in this context
I0522 09:28:02.429455   32016 cached_discovery.go:78] skipped caching discovery info due to an error on the server ("Internal Server Error: \"/apis/metering.ibm.com/v1?timeout=32s\": Post https://172.30.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews: http2: no cached connection was available") has prevented the request from succeeding
```
This line of error `Post https://172.30.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews: http2: no cached connection was available` appears multiple times in different scenarios. Do you know what it means?

**Comment by yue9944882** [comment] 2020-05-28 11:14
> https://172.30.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews: http2: no cached connection was available


i found similar issues in the kubernetes upstream repo: 
https://github.com/kubernetes/kubernetes/pull/53318#issue-144103905
https://github.com/kubernetes/kubernetes/issues/33557


it seems like a scalability issue in http2 go libraries.. not sure how to deal w/ the issue, let me take a further look

**Closed** 2020-10-25 13:43 UTC
Labels: lifecycle/rotten
